"""Add user_id to user_responses

Revision ID: 595c83384d64
Revises: aeb53e1b4daf
Create Date: 2025-09-03 02:58:50.830923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595c83384d64'
down_revision = 'aeb53e1b4daf'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_user_responses_user_id',  # give the constraint a name
            'user',                       # target table
            ['user_id'],                  # local column
            ['user_id']                   # remote column
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_responses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
