"""Add embedding column to user_diary

Revision ID: 63ccf7ea58f2
Revises: 595c83384d64
Create Date: 2025-09-03 22:36:20.007375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63ccf7ea58f2'
down_revision = '595c83384d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', sa.LargeBinary(), nullable=True))

    with op.batch_alter_table('user_diary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_diary', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    # ### end Alembic commands ###
